### ISSUE TITLE
Cannot run the game

### ISSUE THREAD

**Issue by GaryHilares** [kcoder63/SuperMaxioCheckers_snakes-hackers#1]
**Describe the bug**
When I attempt run the game it doesn't open and the following error appears:
```
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\SuperMaxioCheckers_snakes-hackers\main.py", line 4, in <module>
    from minimax.algorithm import minimax
ModuleNotFoundError: No module named 'minimax'
```

According to README.md, there should be a Python file to run the game on Windows. However, it does not exist.

**To Reproduce**
1. Clone the repo.
2. Run the game with "py main.py".

**Expected behavior**
The game should run.

**Desktop (please complete the following information):**
 - OS: Windows 10.

**Additional context:**
This probably is because of the address of `minimax.algorithm` module.

**Comment by GaryHilares** [comment]
I have created a PR regarding this issue. The problem was that instead of `minimax.algorithm` it should be `checkers.minimax.algorithm` because the package `minimax` is inside the package `checkers`.

**Comment by starlightknown** [comment]
Thank you so much for raising the issue and fixing it :)

**Comment by GaryHilares** [comment]
No problem. BTW you have to accept and merge the PR.

**Comment by starlightknown** [comment]
yep done
