### ISSUE TITLE
Image in README does not exist.

### ISSUE THREAD

**Issue by GaryHilares** [kcoder63/SuperMaxioCheckers_snakes-hackers#17]
**Describe the bug**
The README.md image does not exist. It appears that it could not be loaded.

**To Reproduce**
1. Go to the 'README'
2. See error.

**Expected behavior**
The image label should disappear or the image should actually appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/46727048/116788188-e54b3300-aa6d-11eb-8d18-af0eb4d21d7f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10.
 - Browser: Chrome.
 - Browser Version: 90.

**Additional context**
The image was deleted in one of the last commits, but the `img` tag was not removed from the README.

**Comment by starlightknown** [comment]
Yeah I'll fix it, I wanted to replace it with gif

**Comment by starlightknown** [comment]
@all-contributors please add @GaryNLOL for code and bug
