### ISSUE TITLE
RGB value displays instead of color name

### ISSUE THREAD

**Issue by GaryHilares** [kcoder63/SuperMaxioCheckers_snakes-hackers#18]
**Describe the bug**
When you win, the RGB color value of your pieces (`(255,0,0)`) is displayed instead of the word "Red", which is what was supposed to appear.

**To Reproduce**
1. Win the game.
2. Read the message box.

**Expected behavior**
It should say "Red" instead of its RGB value.

**Screenshots**
![image](https://user-images.githubusercontent.com/46727048/116788726-e0d44980-aa70-11eb-82a2-656997aa4652.png)

**Desktop (please complete the following information):**
 - OS: Windows 10.

**Comment by starlightknown** [comment]
Yep I noticed that but still made a commit since didn't want to lose the progress, I'll see what can be done to fix it, you could suggest something if you can
