### ISSUE TITLE
Game ends with an error when you stalemate your opponent

### ISSUE THREAD

**Issue by GaryHilares** [kcoder63/SuperMaxioCheckers_snakes-hackers#19]
**Describe the bug**
When you win your opponent the program ends and throws the following errror:

```python
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Pygame\SuperMaxioCheckers_snakes-hackers\main.py", line 43, in <module>
    main()
  File "C:\Users\Administrator\Desktop\Pygame\SuperMaxioCheckers_snakes-hackers\main.py", line 29, in main
    if game.winner() != None:
  File "C:\Users\Administrator\Desktop\Pygame\SuperMaxioCheckers_snakes-hackers\checkers\game.py", line 23, in winner
    return self.board.winner()
AttributeError: 'NoneType' object has no attribute 'winner'
```

**To Reproduce**
1. Stalemate your opponent.
2. See the output in the command line.

**Expected behavior**
Game should end without error, with the Red as winner.

**Desktop (please complete the following information):**
 - OS: Windows 10.

**Comment by starlightknown** [comment]
Do you have any idea why is it happening? I tried hard and made changes but not able to fix it

**Comment by GaryHilares** [comment]
I'm working on it. BTW here are the screenshots you asked me earlier:

Before moving:
![image](https://user-images.githubusercontent.com/46727048/116790411-9d320d80-aa79-11eb-8f1f-4de765539cd5.png)

After moving and stalemating blue:
![image](https://user-images.githubusercontent.com/46727048/116790458-de2a2200-aa79-11eb-8cd7-c84d87c1cbd3.png)

**Comment by GaryHilares** [comment]
I have just discovered why this is happening.

The problem is related to the following block of code:
```python
if game.turn == BLUE:
            value, new_board = minimax(game.get_board(), 3, BLUE, game)
            game.ai_move(new_board)
```
You are calling `minimax` and then setting the board to the move that `BLUE` makes. However, if `BLUE` is stalemated, the `minimax` function does not analyse any moves, because there are no legal moves. In consequence, it returns the value which was assigned to `best_move` variable in its initialization in `minimax`, which is `None`.

Then comes the next line:
```python
winner = game.winner()
```
Which calls `self.board.winner()`. However, in this call, `board` is `None`, and therefore does not have an attribute called `winner`, which causes the error.

I'm working in a solution for this.

**Comment by starlightknown** [comment]
Oh I see now and thank you for helping out so much!! You're awesome 💥
