### ISSUE TITLE
Switch file order

### ISSUE THREAD

**Issue by GaryHilares** [kcoder63/SuperMaxioCheckers_snakes-hackers#4]
**Is your feature request related to a problem? Please describe.**
This is more a design decision. It does not makes much sense that `minimax` is a package that contains an `algorithm` module. Instead, it would be more logical for a `algorithm` package to exist and include a `minimax` module. `algorithm` is not a `minimax`, `minimax` is an `algorithm`.

**Describe the solution you'd like**
I think the best design decision would be to invert the order and make a package called `algorithm` with a module called `minimax`. This makes more sense and will prevent organization problems in the future.

**Describe alternatives you've considered**
Other than the solution that I've presented and that I consider the best, there are other 2 main options:
- Let it as it is right now. This does not make sense and will cause organization problems in the future as the project gets larger because will force as to create multiple packages just for algorithms and many of them will have just 1 file.
- Instead of making a package called `algorithm` and a module called `minimax` we could just use a module called `algorithm` that includes a `minimax` function on it. This makes sense, but in the future may cause disorganization as the project gets larger because every single algorithm will have to be in the same file.

**Comment by starlightknown** [comment]
Thank you for helping me to improve this project. I agree but I don't think that there will be more algorithms in the package in future, but I'd consider the first solution you suggested and make a package `algorithm` with `minimax` module.
