### ISSUE TITLE
Game ends with an error when you win

### ISSUE THREAD

**Issue by GaryHilares** [kcoder63/SuperMaxioCheckers_snakes-hackers#8]
**Describe the bug**
When you win your opponent the program ends and throws the following errror:
```python
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\SuperMaxioCheckers_snakes-hackers\main.py", line 43, in <module>
    main()
  File "C:\Users\Administrator\Desktop\SuperMaxioCheckers_snakes-hackers\main.py", line 29, in main
    if game.winner() != None:
  File "C:\Users\Administrator\Desktop\SuperMaxioCheckers_snakes-hackers\checkers\game.py", line 23, in winner
    return self.board.winner()
AttributeError: 'NoneType' object has no attribute 'winner'
```

**To Reproduce**
1. Run the game.
2. Win.

**Expected behavior**
Game should end sucessfully without throwing errors.

**Desktop (please complete the following information):**
 - OS: Windows 10.

**Comment by GaryHilares** [comment]
I have just checked this and the error is still present in the latest version of the main branch.

**Comment by starlightknown** [comment]
Could you share some screenshot?

**Comment by GaryHilares** [comment]
I have checked it again and I have just noticed that this no longer happens when you win by capturing all your opponent's pieces, only happens when you win by stalemating your opponent. I'm going to open a new issue that reflects this.
